#tesseract.data.path=/usr/share/tesseract-ocr/4.00/tessdata

receipt.preprocessing.denoise.strength=25
receipt.preprocessing.contrast.limit=4

# Tesseract configuration
tesseract.data.path=C:/Program Files/Tesseract-OCR/tessdata
tesseract.language=rus
tesseract.page.segmentation.mode=6
tesseract.ocr.engine.mode=3

receipt.recognition.confidence.threshold=60

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html